<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>LogicBuilder.Forms.Parameters</RootNamespace>
    <PackageId>LogicBuilder.Forms.Parameters</PackageId>
		<Authors>BlaiseD</Authors>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>true</WarningsAsErrors>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Description>The ConnectorParameters class holds information about the Connector Shape on the flow diagram including additional metadata which typically carries information about a UI button (represented by the connector) and its behaviors.</Description>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>Moving expression parameter classes to a common library.</PackageReleaseNotes>
    <PackageTags>logic-builder rules connector</PackageTags>
    <Copyright>Copyright © BPS 2017</Copyright>
    <RepositoryUrl>https://github.com/BpsLogicBuilder/LogicBuilder.Forms.Parameters</RepositoryUrl>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/BlaiseD/LogicBuilder</PackageProjectUrl>
    <AssemblyOriginatorKeyFile>..\LogicBuilder.Rules.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\icon.png" Pack="true" PackagePath="\" Visible="False" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="LogicBuilder.Attributes" Version="2.0.6" />
    <PackageReference Include="LogicBuilder.Structures" Version="8.0.1" />
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="All" />
  </ItemGroup>

</Project>
